name: 'Check spelling'

on:
  push:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Run spell check
        uses: streetsidesoftware/cspell-action@v2
        with:
          incremental_files_only: true
