name: 'Check spelling'

on:
  push:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Run spell check
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Install cspell
        run: npm install -g cspell
      - name: Build the project 
        run: make
