name: 'Check spelling'

on:
  push:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Run spell check
        with:
          node-version: "latest"
      - run: npm install -g cspell
      - run: make
